### ISSUE TITLE
watching機能の実装

### ISSUE THREAD

**Issue by kabane** [takoaki06/crowdfunding#28]
## 要望
自分が指定したカテゴリーに該当するProductが新着順に見れるページがほしい

## 要件
- 新たにwatchingというController及びModelを追加する
- watchingsテーブルのカラム構成は以下と通りとなり、実質usersとcategoriesの中間テーブルとなる(UserとCategoryはwatchingを通し多対多の関係となる)
```
user_id:integer
categori_id:integer
```
- WatchingsControllerのアクションはindexのみとなる
- WatchingsController#indexのリンクはUsersController#showに設ける
- WatchingsController#indexではcurrent_user.watchings経由で引いたカテゴリーに該当するproductsの一覧を表示する
- watchingsの作成/更新はUserControllers#editから行う(「usersとwatchingsの関係」は「productsとproduct_categories」の関係とほぼ同じと思って良い)

**Comment by takoaki06** [comment]
要望と要件に理解できないところがあり苦戦しておりました。
まず、UserとCategoryの中間テーブル(wacthing)を作るというところは理解し実装しました。

要望の
> 自分が指定したカテゴリーに該当するProductが新着順に見れるページがほしい

とは、例えば「音楽」のカテゴリーであれば、「音楽」のカテゴリーの自身のProductの一覧を表示させたい、という理解で合っていますでしょうか？

> watchingsの作成/更新はUserControllers#editから行う(「usersとwatchingsの関係」は「productsとproduct_categories」の関係とほぼ同じと思って良い)

ProductControllers#editの時のようにCategoryをセレクトボックス形式で選択させる、という認識で合っていますでしょうか？

**Comment by kabane** [comment]
> とは、例えば「音楽」のカテゴリーであれば、「音楽」のカテゴリーの自身のProductの一覧を表示させたい、という理解で合っていますでしょうか？
ですです。イメージ的には「Userが自分が気になるカテゴリーを登録しておく」とWatchingsController#indexでそのカテゴリーを持ったProductが表示されるイメージですね！

> ProductControllers#editの時のようにCategoryをセレクトボックス形式で選択させる、という認識で合っていますでしょうか？
概ね合ってます！ただセレクトボックスではなくチェックボックスですね。

**Comment by takoaki06** [comment]
@kabane 

ありがとうございます。
> ただセレクトボックスではなくチェックボックスですね。

確かにそうです、間違えました。
