### ISSUE TITLE
プロダクト作成機能を追加したい

### ISSUE THREAD

**Issue by kabane** [takoaki06/crowdfunding#3]
## 要件
ログインを行ったユーザーが自身のプロダクトを追加できるようにしたい

## 要望
- ProductのModel,Controller,ViewをScaffoldで作成してみましょう
- UserとProductが1対多になるようにリレーションを追加してみましょう
- productsテーブルのカラムは以下でお願いします
```
title: string
desc: string
user_id: integer
```

**Comment by takoaki06** [comment]
承知しました。
